### ISSUE TITLE
/QueryBuilder/ExecuteQuery is throwing error for nested queries

### ISSUE THREAD

**Issue by igdmdimitrov** [IgniteUI/NorthwindAPI#58]
Open [https://www.infragistics.com/products/ignite-ui-angular/angular/components/query-builder#angular-query-builder-example](https://www.infragistics.com/products/ignite-ui-angular/angular/components/query-builder#angular-query-builder-example)

Condition `customerId equals VINET` is working

Condition `customerId in Customers\customerId` is not working

![Image](https://github.com/user-attachments/assets/7f33f7d8-1226-4678-b60c-180fdaaa5c4f)

**Comment by pmoleri** [comment]
Hi. Sorry about this. This PR #59 should fix the regression.

**Comment by igdmdimitrov** [comment]
> Hi. Sorry about this. This PR [#59](https://github.com/IgniteUI/NorthwindAPI/pull/59) should fix the regression.

@pmoleri , I still get the errors on my end. Is it working for you with the sample linked in the issue description?

**Comment by pmoleri** [comment]
Yes. An even more levels.
Perhaps you didn't check running the PR branch.
I merged it so we don't keep waiting for the fix, it will be deployed soon.
